job('First-Maven-Project-Via-DSC') { 
	description("First Maven job generated by the DSL on ${new Date()}, Maven project hosted on github"
	scm { 
		git("https://github.com/ucodes/Maven-Docker.git", master) 
	}
	triggers { 
		scm('* * * * *')
	} 
	steps { 
		maven('clean package', 'Maven-Docker/pom.xml') 
	}
	publishers { 
		//archive the war file generated
		archiveArtifacts '**/*.jar' 
	} 
}
